version: '3'
services:
  identity-svc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 9080:9080
    depends_on:
       - zipkin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411